fix🐛: 修复 Actions 运行 pytest 报错的问题
```bash
Run uv run --with dev python -m pytest
  uv run --with dev python -m pytest
  shell: /usr/bin/bash -e {0}
  env:
    UV_PUBLISH_TOKEN: ***
    UV_LINK_MODE: copy
    UV_PYTHON: 3.12
    UV_CACHE_DIR: /tmp/setup-uv-cache

  × No solution found when resolving `--with` dependencies:
  ╰─▶ Because dev was not found in the package registry and you require dev,
      we can conclude that your requirements are unsatisfiable.
Error: Process completed with exit code 1.
```