fix🐛: 修复 Actions uv sync --forzen 报错
```bash
Run uv sync --frozen
  uv sync --frozen
  shell: /usr/bin/bash -e {0}
  env:
    UV_PUBLISH_TOKEN: ***
    UV_LINK_MODE: copy
    UV_PYTHON: 3.12
    UV_CACHE_DIR: /tmp/setup-uv-cache
Using Python 3.12.5
Creating virtualenv at: .venv
Failed to parse lockfile; ignoring locked requirements: TOML parse error at line 2601, column 1
     |
2601 | [[package]]
     | ^^^^^^^^^^^
missing field `version`
error: Unable to find lockfile at `uv.lock`. To create a lockfile, run `uv lock` or `uv sync`.
Error: Process completed with exit code 2.
```